In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('train.csv')
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [7]:
df.groupby(['Sex','Pclass']).count()

               PassengerId  Survived  Name  Age  SibSp  Parch  Ticket  Fare  \
Sex    Pclass
female 1                94        94    94   85     94     94      94    94
       2                76        76    76   74     76     76      76    76
       3               144       144   144  102    144    144     144   144
male   1               122       122   122  101    122    122     122   122
       2               108       108   108   99    108    108     108   108
       3               347       347   347  253    347    347     347   347

               Cabin  Embarked
Sex    Pclass
female 1          81        92
       2          10        76
       3           6       144
male   1          95       122
       2           6       108
       3           6       347

In [8]:
df.groupby(['Sex','Pclass'])['Age'].mean()

Sex     Pclass
female  1         34.611765
        2         28.722973
        3         21.750000
male    1         41.281386
        2         30.740707
        3         26.507589
Name: Age, dtype: float64